name: JSON Vault

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ${{ github.repositoryUrl }}
      IMAGE_NAME: ghcr.io/${{ github.repository }}/build:${{ github.sha }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build image
      run: |
        docker build -t "${IMAGE_NAME}" \
               --label "org.opencontainers.image.source=${REPOSITORY_URL}" \
               docker
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to GitHub Containers Registry
      run: |
        docker push "${IMAGE_NAME}"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        py.test --cov=./ --cov-report=xml tests
    - name: Publish coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-ut
        fail_ci_if_error: true

